wandb_version: 1

learning rate:
  desc: null
  value: 0.0001
max epochs per new maze:
  desc: null
  value: 1000
maze width:
  desc: null
  value: 6
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1687195768.303956
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.13
      5: 0.15.4
      8:
      - 1
      - 3
      - 5
