wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1687102095.08693
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 34
      4: 3.9.13
      5: 0.15.4
      8:
      - 1
      - 3
      - 5
