wandb_version: 1

eps_train:
  desc: null
  value: 0.95
eps_test_eps:
  desc: null
  value: 0.0
eps_decay:
  desc: null
  value: 0.999
eps_min:
  desc: null
  value: 0.1
learning rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 512
gamma:
  desc: null
  value: 0.9
n_step:
  desc: null
  value: 3
target_update_freq:
  desc: null
  value: 100
buffer_size:
  desc: null
  value: 30000
step_per_epoch:
  desc: null
  value: 10000
step_per_collect:
  desc: null
  value: 200
ep_per_collect:
  desc: null
  value: 1
maze width:
  desc: null
  value: 6
n_mazes:
  desc: null
  value: 0
total_mazes:
  desc: null
  value: 36
threshold_rew:
  desc: null
  value: 0.5
non-marl:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1687277543.669119
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.13
      5: 0.15.4
      8:
      - 1
      - 3
      - 5
